application: mirai-shokudo
version: 1
#version: dev-test
runtime: php
api_version: 1

handlers:
- url: /
  static_files: index.html
  upload: index.html

- url: /(.*)
  static_files: \1
  upload: (.*)